import type { ArtistRole, LegalStatus, ProjectCategory } from "./schema";
import type { OrganismeId } from "./organismes";
export type DispositifId="CNM_PROD_PHONO"|"CNM_SPECTACLE_VIVANT"|"CNM_MUSIQUE_EN_IMAGES"|"SACEM_AIDE_CREATION"|"ADAMI_365"|"SPEDIDAM_AIDE_PROJET"|"DRAC_AIDE_CREATION";
export interface Dispositif { id:DispositifId; organismeId:OrganismeId; name:string; description:string; officialUrl:string; eligibleCategories:ProjectCategory[]; eligibleRoles:ArtistRole[]|"ANY"; excludedLegalStatuses?:LegalStatus[]; requiredAffiliationField?:"sacem_id"|"adami_id"|"spedidam_id"|"cnm_space_id"; requiredDocuments:string[]; territoire:string; typicalWindow:string; active:boolean; lastVerifiedAt:string; sourceNote?:string; }
export const DISPOSITIFS:Dispositif[]=[
{id:"CNM_PROD_PHONO",organismeId:"CNM",name:"Aide à la production phonographique",description:"Soutient les coûts de studio, mixage, mastering et fabrication d'un enregistrement.",officialUrl:"https://cnm.fr/aides-financieres/aide-a-la-production-phonographique-3/",eligibleCategories:["RECORDING_ALBUM_EP"],eligibleRoles:"ANY",excludedLegalStatuses:["PARTICULIER"],requiredAffiliationField:"cnm_space_id",requiredDocuments:["Kbis ou SIRENE","RIB","Devis studio"],territoire:"National",typicalWindow:"Dépôt continu, plusieurs commissions par an",active:true,lastVerifiedAt:"2026-09-25"},
{id:"CNM_SPECTACLE_VIVANT",organismeId:"CNM",name:"Aide à la production et à la diffusion de spectacle vivant",description:"Soutient la production d'un spectacle, les répétitions et un plan de diffusion en tournée.",officialUrl:"https://cnm.fr/aides-financieres/aide-a-la-production-et-a-la-diffusion-de-spectacle-vivant/",eligibleCategories:["LIVE_SHOW_TOUR"],eligibleRoles:"ANY",excludedLegalStatuses:["PARTICULIER"],requiredAffiliationField:"cnm_space_id",requiredDocuments:["Kbis ou SIRENE","RIB","Plan de tournée ou dates contractualisées"],territoire:"National",typicalWindow:"Commissions 2026 : 18 mars, 13 mai, 26 août",active:true,lastVerifiedAt:"2026-09-25"},
{id:"CNM_MUSIQUE_EN_IMAGES",organismeId:"CNM",name:"Aide à la production de musique en images",description:"Soutient la réalisation d'un clip ou contenu vidéo musical lié à une activité phonographique.",officialUrl:"https://cnm.fr/aides-financieres/",eligibleCategories:["MUSIC_VIDEO"],eligibleRoles:"ANY",excludedLegalStatuses:["PARTICULIER"],requiredAffiliationField:"cnm_space_id",requiredDocuments:["Kbis ou SIRENE","RIB","Devis de production vidéo"],territoire:"National",typicalWindow:"Commissions 2026 : 3 avril, 3 juin, 15 juillet",active:true,lastVerifiedAt:"2026-09-25",sourceNote:"URL générale du portail CNM : lien direct du dispositif à vérifier avant dépôt."},
{id:"SACEM_AIDE_CREATION",organismeId:"SACEM",name:"Aide à l’autoproduction",description:"Soutient la 1re, 2e ou 3e autoproduction d’un enregistrement finalisé en musiques actuelles, comportant au moins 5 titres et bénéficiant d’un environnement professionnel.",officialUrl:"https://aide-aux-projets.sacem.fr",eligibleCategories:["RECORDING_ALBUM_EP"],eligibleRoles:["COMPOSITEUR","BEATMAKER"],requiredAffiliationField:"sacem_id",requiredDocuments:["Numéro de membre SACEM","Enregistrement finalisé (au moins 5 titres)","Justificatif d’environnement professionnel"],territoire:"National",typicalWindow:"Programme SACEM 2026 — calendrier à vérifier sur Aide aux projets avant dépôt",active:true,lastVerifiedAt:"2026-09-26",sourceNote:"Programme Aide à l’autoproduction. Montant forfaitaire annoncé : 5 000 €. Vérifier le calendrier et les modalités dans l’espace Aide aux projets au moment du dépôt."},
{id:"ADAMI_365",organismeId:"ADAMI",name:"Adami 365 — Aide au projet musical global",description:"Aide directe aux artistes-producteurs associés de l’Adami pour un projet musical global sur 12 mois comprenant obligatoirement un enregistrement et au moins deux autres volets parmi spectacle, promotion et production audiovisuelle.",officialUrl:"https://www.adami.fr/que-fait-ladami-pour-moi/cherche-financement-projet-artistique/projet-musical-global/",eligibleCategories:["RECORDING_ALBUM_EP"],eligibleRoles:["CHANTEUR","RAPPEUR","INSTRUMENTISTE","DJ"],excludedLegalStatuses:["PARTICULIER"],requiredAffiliationField:"adami_id",requiredDocuments:["Trame budgétaire prévisionnelle Adami 365","Présentation détaillée de l’artiste et du projet global","Éléments justifiant les dépenses et financements","Contrat d’enregistrement / contrat d’artiste","Contrat de distribution ou licence le cas échéant"],territoire:"National",typicalWindow:"Commission Musique environ toutes les 6 semaines, hors juillet et août",active:true,lastVerifiedAt:"2026-09-26",sourceNote:"Avant dépôt, l’artiste doit contacter l’Adami afin que son accès au dispositif soit vérifié et qu’une trame budgétaire lui soit transmise. Dépôt ensuite sur i-DA. Les prises de l’enregistrement ne doivent pas être terminées au passage en commission et les projets audiovisuels ne doivent jamais avoir été diffusés."},
{id:"SPEDIDAM_AIDE_PROJET",organismeId:"SPEDIDAM",name:"Aide aux projets collectifs",description:"Aide les artistes-interprètes sur des projets collectifs pour la tournée et l'enregistrement.",officialUrl:"https://www.spedidam.fr/aides-aux-projets/demander-aide/",eligibleCategories:["LIVE_SHOW_TOUR","RECORDING_ALBUM_EP"],eligibleRoles:["CHANTEUR","RAPPEUR","INSTRUMENTISTE","DJ"],requiredAffiliationField:"spedidam_id",requiredDocuments:["Numéro SPEDIDAM","Liste des artistes-interprètes du projet"],territoire:"National",typicalWindow:"Commissions bimestrielles",active:true,lastVerifiedAt:"2026-09-25"},
{id:"DRAC_AIDE_CREATION",organismeId:"DRAC",name:"Aide régionale à la création",description:"Financement régional de la création, souvent complémentaire aux aides nationales.",officialUrl:"https://www.culture.gouv.fr/regions",eligibleCategories:["CREATION_RESIDENCY","LIVE_SHOW_TOUR"],eligibleRoles:"ANY",excludedLegalStatuses:["PARTICULIER"],requiredDocuments:["Dossier artistique","Budget prévisionnel détaillé","Lettre de soutien d'un lieu partenaire"],territoire:"Régional (modalités variables selon la DRAC)",typicalWindow:"1 à 2 commissions par an selon la région",active:true,lastVerifiedAt:"2026-09-25",sourceNote:"Chaque DRAC régionale publie ses propres critères et échéances, à vérifier localement."}
];
export function getDispositif(id:DispositifId):Dispositif { const d=DISPOSITIFS.find(x=>x.id===id); if(!d) throw new Error(`Dispositif inconnu : ${id}`); return d; }
export function getDispositifsByOrganisme(organismeId:OrganismeId):Dispositif[] { return DISPOSITIFS.filter(d=>d.organismeId===organismeId); }
