"use client";
import { create } from "zustand";
import { persist } from "zustand/middleware";
import { emptyApplication,type ApplicantProfile,type MasterMusicApplication,type ProjectAttachment,type ProjectDetails } from "@/lib/schema";
import { makeNotification,type AppNotification } from "@/lib/notifications";
import type { VaultDocument,VaultDocumentKind } from "@/lib/documents";
import { computeDispositifMatches } from "@/lib/eligibility";
import type { ApplicationSubmissionRecord,Dossier,DossierDispositifTracking,DossierStatus,DispositifTrackingStatus } from "@/lib/dossier";
import type { DispositifId } from "@/lib/dispositifs";
export const ONBOARDING_STEPS=["statut","roles","identite","photo"] as const;
export type OnboardingStep=(typeof ONBOARDING_STEPS)[number];
export const DOSSIER_STEPS=["projet","documents","recapitulatif"] as const;
export type DossierStep=(typeof DOSSIER_STEPS)[number];
const emptyProjectDetails:ProjectDetails={categories:[],attachments:[]};
interface ApplicationState{
 application:MasterMusicApplication;documents:Partial<Record<VaultDocumentKind,VaultDocument>>;notifications:AppNotification[];dossiers:Dossier[];
 updateProfile:(patch:Partial<ApplicantProfile>)=>void;updateAffiliations:(patch:Partial<ApplicantProfile["affiliations"]>)=>void;updateCatalogLinks:(patch:Partial<ApplicantProfile["catalog_links"]>)=>void;updateProject:(patch:Partial<ProjectDetails>)=>void;
 addProjectAttachment:(attachment:ProjectAttachment)=>void;removeProjectAttachment:(attachmentId:string)=>void;setDocument:(kind:VaultDocumentKind,doc:VaultDocument|null)=>void;validateDocument:(kind:VaultDocumentKind)=>void;
 addNotification:(n:AppNotification)=>void;markNotificationRead:(id:string)=>void;markAllNotificationsRead:()=>void;clearNotifications:()=>void;submitCurrentDossier:()=>string;
 updateDossierFunder:(dossierId:string,dispositifId:DispositifId,patch:Partial<DossierDispositifTracking>)=>void;updateDossierStatus:(dossierId:string,status:DossierStatus)=>void;addDossierProjectAttachment:(dossierId:string,attachment:ProjectAttachment)=>void;
 toggleDossierChecklistItem:(dossierId:string,item:string)=>void;deleteDossier:(dossierId:string)=>void;updateDossierApplicationField:(dossierId:string,dispositifId:DispositifId,fieldId:string,value:string)=>void;
 updateDossierApplicationDraft:(dossierId:string,dispositifId:DispositifId,fieldId:string,text:string,accepted:boolean)=>void;validateDossierApplication:(dossierId:string,dispositifId:DispositifId,submission:ApplicationSubmissionRecord)=>void;recordDossierExport:(dossierId:string,dispositifId:DispositifId)=>void;resetApplication:()=>void;
}
export const useApplicationStore=create<ApplicationState>()(persist((set,get)=>({
 application:emptyApplication,documents:{},notifications:[makeNotification("Bienvenue sur Subvento","Complétez votre profil une seule fois pour candidater auprès du CNM, de la SACEM, de l'ADAMI, de la SPEDIDAM et de la DRAC.","info")],dossiers:[],
 updateProfile:(patch)=>set(s=>({application:{...s.application,applicant_profile:{...s.application.applicant_profile,...patch}}})),
 updateAffiliations:(patch)=>set(s=>({application:{...s.application,applicant_profile:{...s.application.applicant_profile,affiliations:{...s.application.applicant_profile.affiliations,...patch}}}})),
 updateCatalogLinks:(patch)=>set(s=>({application:{...s.application,applicant_profile:{...s.application.applicant_profile,catalog_links:{...s.application.applicant_profile.catalog_links,...patch}}}})),
 updateProject:(patch)=>set(s=>({application:{...s.application,project_details:{...s.application.project_details,...patch}}})),
 addProjectAttachment:(attachment)=>set(s=>({application:{...s.application,project_details:{...s.application.project_details,attachments:[...(s.application.project_details.attachments??[]),attachment]}}})),
 removeProjectAttachment:(attachmentId)=>set(s=>({application:{...s.application,project_details:{...s.application.project_details,attachments:(s.application.project_details.attachments??[]).filter(a=>a.id!==attachmentId)}}})),
 setDocument:(kind,doc)=>set(s=>{const documents={...s.documents};if(doc)documents[kind]=doc;else delete documents[kind];return{documents,application:{...s.application,vault_documents:{...s.application.vault_documents,[kind]:doc?doc.id:""}}};}),
 validateDocument:(kind)=>{set(s=>{const doc=s.documents[kind];if(!doc)return s;return{documents:{...s.documents,[kind]:{...doc,status:"valide" as const}}};});const labels:Record<VaultDocumentKind,string>={kbis_doc_id:"Kbis / SIRENE",rib_doc_id:"RIB",id_card_doc_id:"pièce d'identité"};get().addNotification(makeNotification("Document validé",`Votre ${labels[kind]} a été vérifié et validé dans le coffre-fort.`,"success"));},
 addNotification:(n)=>set(s=>({notifications:[n,...s.notifications]})),markNotificationRead:(id)=>set(s=>({notifications:s.notifications.map(n=>n.id===id?{...n,read:true}:n)})),markAllNotificationsRead:()=>set(s=>({notifications:s.notifications.map(n=>({...n,read:true}))})),clearNotifications:()=>set({notifications:[]}),
 submitCurrentDossier:()=>{const s=get();const matches=computeDispositifMatches(s.application.applicant_profile,s.application.project_details);const id=crypto.randomUUID();const dossier:Dossier={id,project:s.application.project_details,status:"pret",createdAt:new Date().toISOString(),submittedAt:new Date().toISOString(),dispositifs:matches.map(m=>({dispositifId:m.dispositif.id,status:(m.state==="compatible"?"eligible":"non_eligible") as DispositifTrackingStatus,montantDemande:null,montantPercu:null})),checkedItems:[]};set(state=>({dossiers:[dossier,...state.dossiers],application:{...state.application,project_details:{...emptyProjectDetails}}}));get().addNotification(makeNotification("Dossier prêt",`Votre dossier « ${dossier.project.title??"sans titre"} » est prêt. Il ne sera réellement instruit qu'une fois déposé par vos soins sur le site de chaque organisme.`,"success"));return id;},
 updateDossierFunder:(dossierId,dispositifId,patch)=>set(s=>({dossiers:s.dossiers.map(d=>d.id!==dossierId?d:{...d,dispositifs:d.dispositifs.map(f=>f.dispositifId===dispositifId?{...f,...patch}:f)})})),
 updateDossierStatus:(dossierId,status)=>set(s=>({dossiers:s.dossiers.map(d=>d.id===dossierId?{...d,status}:d)})),
 addDossierProjectAttachment:(dossierId,attachment)=>set(s=>({dossiers:s.dossiers.map(d=>d.id!==dossierId?d:{...d,project:{...d.project,attachments:[...(d.project.attachments??[]),attachment]}})})),
 updateDossierApplicationField:(dossierId,dispositifId,fieldId,value)=>set(s=>({dossiers:s.dossiers.map(d=>d.id!==dossierId?d:{...d,dispositifs:d.dispositifs.map(f=>f.dispositifId!==dispositifId?f:{...f,manualFieldValues:{...(f.manualFieldValues??{}),[fieldId]:value}})})})),
 updateDossierApplicationDraft:(dossierId,dispositifId,fieldId,text,accepted)=>set(s=>({dossiers:s.dossiers.map(d=>d.id!==dossierId?d:{...d,dispositifs:d.dispositifs.map(f=>f.dispositifId!==dispositifId?f:{...f,draftValues:{...(f.draftValues??{}),[fieldId]:{text,accepted}}})})})),
 validateDossierApplication:(dossierId,dispositifId,submission)=>{set(s=>({dossiers:s.dossiers.map(d=>d.id!==dossierId?d:{...d,dispositifs:d.dispositifs.map(f=>f.dispositifId!==dispositifId?f:{...f,status:"pret",submission})})}));get().addNotification(makeNotification("Dossier validé","Vous avez confirmé l'exactitude des informations. Le dossier est prêt — le dépôt reste une action que vous effectuez vous-même.","success"));},
 recordDossierExport:(dossierId,dispositifId)=>set(s=>({dossiers:s.dossiers.map(d=>d.id!==dossierId?d:{...d,dispositifs:d.dispositifs.map(f=>f.dispositifId!==dispositifId||!f.submission?f:{...f,submission:{...f.submission,depositMode:"export",exportedAt:new Date().toISOString()}})})})),
 toggleDossierChecklistItem:(dossierId,item)=>set(s=>({dossiers:s.dossiers.map(d=>{if(d.id!==dossierId)return d;const checked=new Set(d.checkedItems??[]);if(checked.has(item))checked.delete(item);else checked.add(item);return{...d,checkedItems:Array.from(checked)};})})),
 deleteDossier:(dossierId)=>set(s=>({dossiers:s.dossiers.filter(d=>d.id!==dossierId)})),
 resetApplication:()=>set({application:emptyApplication,documents:{},dossiers:[]})
}),{name:"subvento-application",version:6,migrate:(persisted)=>{const state=persisted as Record<string,unknown>&{application?:{project_details?:Record<string,unknown>;applicant_profile?:Record<string,unknown>};dossiers?:Array<Record<string,unknown>>};if(!("dossiers" in state))state.dossiers=[];delete state.submitted;delete state.submittedAt;const project=state.application?.project_details;if(project){if(!Array.isArray(project.categories))project.categories=project.category?[project.category]:[];delete project.category;if(!Array.isArray(project.attachments))project.attachments=[];}(state.dossiers??[]).forEach(d=>{const dp=d.project as Record<string,unknown>|undefined;if(dp){if(!Array.isArray(dp.categories))dp.categories=dp.category?[dp.category]:[];delete dp.category;if(!Array.isArray(dp.attachments))dp.attachments=[];}if(!Array.isArray(d.checkedItems))d.checkedItems=[];});const ORGANISME_DISPOSITIFS:Record<string,string[]>={CNM:["CNM_PROD_PHONO","CNM_SPECTACLE_VIVANT","CNM_MUSIQUE_EN_IMAGES"],SACEM:["SACEM_AIDE_CREATION"],ADAMI:["ADAMI_AIDE_PROJET"],SPEDIDAM:["SPEDIDAM_AIDE_PROJET"],DRAC:["DRAC_AIDE_CREATION"]};(state.dossiers??[]).forEach(d=>{if(d.status==="soumis")d.status="pret";if(Array.isArray(d.funders)&&!Array.isArray(d.dispositifs)){const oldFunders=d.funders as Array<{funderId:string;status:string;montantDemande:number|null;montantPercu:number|null}>;const dispositifs:Array<{dispositifId:string;status:string;montantDemande:number|null;montantPercu:number|null}>=[];Object.entries(ORGANISME_DISPOSITIFS).forEach(([organismeId,ids])=>{const old=oldFunders.find(f=>f.funderId===organismeId);ids.forEach((dispositifId,index)=>dispositifs.push({dispositifId,status:old?.status??"eligible",montantDemande:index===0?old?.montantDemande??null:null,montantPercu:index===0?old?.montantPercu??null:null}));});d.dispositifs=dispositifs;}delete d.funders;});const applicantProfile=state.application?.applicant_profile as Record<string,unknown>|undefined;if(applicantProfile&&!applicantProfile.catalog_links)applicantProfile.catalog_links={};return state as never;},partialize:s=>({application:s.application,documents:s.documents,notifications:s.notifications,dossiers:s.dossiers})}));
