"use client";
import Link from "next/link";
import { ArrowRight, FileCheck2, FolderKanban, Landmark, Sparkles } from "lucide-react";
import { useApplicationStore, ONBOARDING_STEPS } from "@/store/useApplicationStore";
import { computeOverallProgress, isStepComplete } from "@/lib/progress";
import { ORGANISMES } from "@/lib/organismes";
import { getDispositifsByOrganisme } from "@/lib/dispositifs";
import { DOSSIER_STATUS_LABELS, DOSSIER_STATUS_COLORS, dossierTotals } from "@/lib/dossier";
import { formatProjectCategories } from "@/lib/schema";
import { vibrate } from "@/lib/haptics";
export default function Home(){
 const application=useApplicationStore(s=>s.application),documents=useApplicationStore(s=>s.documents),dossiers=useApplicationStore(s=>s.dossiers);
 const requiredOnboardingSteps=ONBOARDING_STEPS.filter(s=>s!=="photo");const profileProgress=computeOverallProgress(requiredOnboardingSteps,application,documents);const profileStarted=profileProgress>0;const onboardingComplete=requiredOnboardingSteps.every(s=>isStepComplete(s,application,documents));const nextOnboardingStep=requiredOnboardingSteps.find(s=>!isStepComplete(s,application,documents));const totalPercu=dossiers.reduce((sum,d)=>sum+dossierTotals(d).percu,0);const recentDossiers=dossiers.slice(0,3);
 const ctaHref=!onboardingComplete?`/onboarding/${nextOnboardingStep??"statut"}`:"/dossier/projet";const ctaLabel=!profileStarted?"Démarrer mon profil":!onboardingComplete?"Compléter mon profil":dossiers.length>0?"Créer un nouveau dossier":"Créer mon premier dossier";
 return <div className="max-w-5xl w-full mx-auto px-5 py-10 sm:py-16 flex-1"><div className="max-w-2xl"><span className="animate-fade-up inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1 rounded-full mb-5" style={{background:"var(--color-gold-soft)",color:"var(--color-gold)",animationDelay:"0ms"}}><Sparkles className="w-3.5 h-3.5"/>Le guichet unique du financement musical</span><h1 className="animate-fade-up text-2xl sm:text-4xl font-semibold tracking-tight leading-tight mb-4" style={{animationDelay:"70ms"}}>Un seul profil. Plusieurs dispositifs. Zéro paperasse répétée.</h1><p className="animate-fade-up text-base leading-relaxed mb-7" style={{color:"var(--color-text-muted)",animationDelay:"140ms"}}>Renseignez votre profil une fois, puis créez autant de dossiers que nécessaire pour candidater au CNM, à la SACEM, à l&apos;ADAMI, à la SPEDIDAM et à la DRAC.</p><div className="animate-fade-up flex flex-wrap items-center gap-3" style={{animationDelay:"210ms"}}><Link href={ctaHref} onClick={()=>vibrate()} className="focus-gold inline-flex items-center gap-2 text-sm font-semibold px-6 py-3 rounded-full" style={{background:"var(--color-gold)",color:"#0a1f1c"}}>{ctaLabel}<ArrowRight className="w-4 h-4"/></Link></div></div>
 <div className="animate-fade-up grid sm:grid-cols-3 gap-4 mt-10" style={{animationDelay:"280ms"}}><div className="card p-5"><FolderKanban className="w-5 h-5 mb-3" style={{color:"var(--color-gold)"}}/><p className="text-2xl font-semibold">{dossiers.length}</p><p className="text-sm mt-1" style={{color:"var(--color-text-muted)"}}>Dossier{dossiers.length>1?"s":""} créé{dossiers.length>1?"s":""}</p></div><div className="card p-5"><Landmark className="w-5 h-5 mb-3" style={{color:"var(--color-gold)"}}/><p className="text-2xl font-semibold" style={{color:totalPercu>0?"var(--color-success)":undefined}}>{totalPercu.toLocaleString("fr-FR")} €</p><p className="text-sm mt-1" style={{color:"var(--color-text-muted)"}}>Montant total perçu</p></div><div className="card p-5"><FileCheck2 className="w-5 h-5 mb-3" style={{color:"var(--color-gold)"}}/><p className="text-2xl font-semibold">{Object.keys(documents).length}<span className="text-sm font-normal" style={{color:"var(--color-text-faint)"}}> / 3</span></p><p className="text-sm mt-1" style={{color:"var(--color-text-muted)"}}>Documents dans le coffre-fort</p></div></div>
 {recentDossiers.length>0&&<div className="mt-10"><div className="flex items-center justify-between mb-3"><h2 className="text-base font-semibold">Dossiers récents</h2><Link href="/dossiers" onClick={()=>vibrate()} className="text-sm font-medium" style={{color:"var(--color-gold)"}}>Tout voir</Link></div><div className="flex flex-col gap-2.5">{recentDossiers.map(d=><Link key={d.id} href={`/dossiers/detail?id=${d.id}`} onClick={()=>vibrate()} className="card card-hover p-4 flex items-center justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold truncate">{d.project.title||"Sans titre"}</p><p className="text-xs mt-0.5" style={{color:"var(--color-text-faint)"}}>{formatProjectCategories(d.project.categories)}</p></div><span className="text-[11px] font-medium px-2 py-1 rounded-full shrink-0" style={{color:DOSSIER_STATUS_COLORS[d.status],background:"var(--color-bg-elevated)"}}>{DOSSIER_STATUS_LABELS[d.status]}</span></Link>)}</div></div>}
 <h2 className="text-base font-semibold mt-10 mb-4">Organismes couverts</h2><div className="grid sm:grid-cols-2 gap-3">{ORGANISMES.map(organisme=>{const dispositifCount=getDispositifsByOrganisme(organisme.id).length;return <div key={organisme.id} className="card p-4 flex items-start gap-3"><span className="w-9 h-9 rounded-lg flex items-center justify-center text-xs font-bold shrink-0" style={{background:`${organisme.color}22`,color:organisme.color}}>{organisme.name.slice(0,2)}</span><div><p className="text-sm font-semibold">{organisme.fullName}<span className="font-normal" style={{color:"var(--color-text-faint)"}}> · {dispositifCount} dispositif{dispositifCount>1?"s":""}</span></p><p className="text-xs mt-1 leading-relaxed" style={{color:"var(--color-text-muted)"}}>{organisme.description}</p></div></div>})}</div></div>;
}