"use client";
import { useRef, useState } from "react";
import { Camera, FileCheck2, FileClock, FileX2, Upload, X } from "lucide-react";
import { useApplicationStore } from "@/store/useApplicationStore";
import { VAULT_DOCUMENT_LABELS, VAULT_DOCUMENT_HINTS, type VaultDocumentKind, type DocumentStatus } from "@/lib/documents";
import { makeNotification } from "@/lib/notifications";
import { vibrate } from "@/lib/haptics";
import { DocumentScanner, type ScannedDocument } from "./DocumentScanner";
const STATUS_META:Record<DocumentStatus,{label:string;color:string;icon:typeof FileCheck2}>={manquant:{label:"Manquant",color:"var(--color-text-faint)",icon:Upload},en_attente:{label:"En cours de vérification",color:"var(--color-warning)",icon:FileClock},valide:{label:"Validé",color:"var(--color-success)",icon:FileCheck2},rejete:{label:"Rejeté — à renvoyer",color:"var(--color-error)",icon:FileX2}};
function readFileAsDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=reject;reader.readAsDataURL(file);});}
export function DocumentUploader({kind}:{kind:VaultDocumentKind}){
 const[dragOver,setDragOver]=useState(false);const[scannerOpen,setScannerOpen]=useState(false);const fileInputRef=useRef<HTMLInputElement>(null);const doc=useApplicationStore(s=>s.documents[kind]);const setDocument=useApplicationStore(s=>s.setDocument);const addNotification=useApplicationStore(s=>s.addNotification);const status:DocumentStatus=doc?.status??"manquant";const meta=STATUS_META[status];const Icon=meta.icon;
 function storeCapture({dataUrl,fileName}:ScannedDocument){setDocument(kind,{id:crypto.randomUUID(),kind,fileName,sizeBytes:Math.round((dataUrl.length*3)/4),mimeType:dataUrl.slice(5,dataUrl.indexOf(";"))||"image/jpeg",dataUrl,uploadedAt:new Date().toISOString(),status:"en_attente"});addNotification(makeNotification("Document reçu",`${VAULT_DOCUMENT_LABELS[kind]} a été ajouté à votre coffre-fort et est en cours de vérification.`,"info"));}
 async function handleFile(file:File){if(file.size>8*1024*1024){addNotification(makeNotification("Fichier trop volumineux",`${file.name} dépasse la limite de 8 Mo.`,"error"));return;}const dataUrl=await readFileAsDataUrl(file);storeCapture({kind,dataUrl,fileName:file.name});}
 return <div className="card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{VAULT_DOCUMENT_LABELS[kind]}</p><p className="text-xs mt-0.5" style={{color:"var(--color-text-faint)"}}>{VAULT_DOCUMENT_HINTS[kind]}</p></div><span className="flex items-center gap-1.5 text-xs font-medium shrink-0" style={{color:meta.color}}><Icon className="w-3.5 h-3.5"/>{meta.label}</span></div>
 {doc?<div className="mt-4 flex items-center justify-between gap-3 rounded-xl px-3.5 py-2.5" style={{background:"var(--color-bg-elevated)",border:"1px solid var(--color-border)"}}><span className="text-sm truncate">{doc.fileName}</span><button type="button" onClick={()=>{vibrate();setDocument(kind,null);}} aria-label="Supprimer le document" className="focus-gold shrink-0 w-7 h-7 rounded-full flex items-center justify-center hover:bg-white/5"><X className="w-4 h-4" style={{color:"var(--color-text-muted)"}}/></button></div>:<div onDragOver={e=>{e.preventDefault();setDragOver(true);}} onDragLeave={()=>setDragOver(false)} onDrop={e=>{e.preventDefault();setDragOver(false);const file=e.dataTransfer.files?.[0];if(file)handleFile(file);}} className="mt-4 rounded-xl transition-colors" style={{border:`1.5px dashed ${dragOver?"var(--color-gold)":"var(--color-border-strong)"}`,background:dragOver?"var(--color-gold-soft)":"transparent"}}><div className="grid grid-cols-2 divide-x" style={{borderColor:"var(--color-border)"}}><button type="button" onClick={()=>{vibrate();setScannerOpen(true);}} className="focus-gold flex flex-col items-center justify-center gap-1.5 py-5" style={{borderColor:"var(--color-border-strong)"}}><Camera className="w-5 h-5" style={{color:"var(--color-text-faint)"}}/><span className="text-xs" style={{color:"var(--color-text-muted)"}}>Scanner</span></button><button type="button" onClick={()=>{vibrate();fileInputRef.current?.click();}} className="focus-gold flex flex-col items-center justify-center gap-1.5 py-5"><Upload className="w-5 h-5" style={{color:"var(--color-text-faint)"}}/><span className="text-xs" style={{color:"var(--color-text-muted)"}}>Importer un PDF</span></button></div></div>}
 <input ref={fileInputRef} type="file" accept=".pdf,image/*" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)handleFile(file);e.target.value="";}}/>
 {scannerOpen&&<DocumentScanner steps={[kind]} onFinish={captures=>{setScannerOpen(false);captures.forEach(storeCapture);}} onClose={()=>setScannerOpen(false)}/>}</div>;
}