"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Check, RotateCcw, Upload, X } from "lucide-react";
import { VAULT_DOCUMENT_LABELS, VAULT_DOCUMENT_SCAN_ASPECT, VAULT_DOCUMENT_SCAN_INSTRUCTIONS, type VaultDocumentKind } from "@/lib/documents";
import { vibrate } from "@/lib/haptics";
export interface ScannedDocument { kind: VaultDocumentKind; dataUrl: string; fileName: string; }
interface DocumentScannerProps { steps: VaultDocumentKind[]; onFinish: (captures: ScannedDocument[]) => void; onClose: () => void; }
type Phase = "requesting" | "camera" | "error" | "review";
function readFileAsDataUrl(file: File): Promise<string> { return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=reject;reader.readAsDataURL(file);}); }
export function DocumentScanner({steps,onFinish,onClose}:DocumentScannerProps){
 const[stepIndex,setStepIndex]=useState(0);const[phase,setPhase]=useState<Phase>("requesting");const[capturedDataUrl,setCapturedDataUrl]=useState<string|null>(null);const[flash,setFlash]=useState(false);
 const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const fileInputRef=useRef<HTMLInputElement>(null);const streamRef=useRef<MediaStream|null>(null);const capturesRef=useRef<ScannedDocument[]>([]);const kind=steps[stepIndex];
 useEffect(()=>{let cancelled=false;async function start(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment",width:{ideal:1920},height:{ideal:1080}},audio:false});if(cancelled){stream.getTracks().forEach(t=>t.stop());return;}streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setPhase("camera");}catch{if(!cancelled)setPhase("error");}}start();return()=>{cancelled=true;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;};},[]);
 function capture(){const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||video.videoWidth===0)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.drawImage(video,0,0,canvas.width,canvas.height);const dataUrl=canvas.toDataURL("image/jpeg",0.88);vibrate(15);setFlash(true);window.setTimeout(()=>setFlash(false),300);setCapturedDataUrl(dataUrl);setPhase("review");}
 function hasLiveStream(){return Boolean(streamRef.current?.getVideoTracks().some(t=>t.readyState==="live"));}
 function retake(){vibrate();setCapturedDataUrl(null);setPhase(hasLiveStream()?"camera":"error");}
 function advanceOrFinish(entry:ScannedDocument){capturesRef.current=[...capturesRef.current,entry];if(stepIndex<steps.length-1){setStepIndex(i=>i+1);setCapturedDataUrl(null);setPhase(hasLiveStream()?"camera":"error");}else{streamRef.current?.getTracks().forEach(t=>t.stop());onFinish(capturesRef.current);}}
 function confirmCapture(){if(!capturedDataUrl)return;vibrate([10,30,15]);advanceOrFinish({kind,dataUrl:capturedDataUrl,fileName:`${kind}-${Date.now()}.jpg`});}
 async function handleFilePicked(file:File){const dataUrl=await readFileAsDataUrl(file);vibrate();advanceOrFinish({kind,dataUrl,fileName:file.name});}
 function handleClose(){vibrate();streamRef.current?.getTracks().forEach(t=>t.stop());onClose();}
 const aspect=VAULT_DOCUMENT_SCAN_ASPECT[kind];
 return <div className="fixed inset-0 z-[200] flex flex-col" style={{background:"#000"}}>
 <div className="relative z-10 flex items-center gap-3 px-4" style={{paddingTop:"calc(env(safe-area-inset-top, 0px) + 14px)",paddingBottom:"14px"}}><button type="button" onClick={handleClose} aria-label="Fermer" className="focus-gold w-9 h-9 rounded-full flex items-center justify-center shrink-0" style={{background:"rgba(255,255,255,0.12)"}}><X className="w-4 h-4" style={{color:"#fff"}}/></button><div className="flex-1 flex items-center gap-1.5">{steps.map((_,i)=><span key={i} className="flex-1 h-1 rounded-full transition-colors" style={{background:i<stepIndex?"var(--color-gold)":i===stepIndex?"rgba(255,255,255,0.9)":"rgba(255,255,255,0.25)"}}/>)}</div><span className="w-9 shrink-0"/></div>
 <div className="relative flex-1 overflow-hidden"><video ref={videoRef} autoPlay playsInline muted className="absolute inset-0 w-full h-full object-cover" style={{display:phase==="camera"?"block":"none"}}/><canvas ref={canvasRef} className="hidden"/>
 {phase==="camera"&&<><div className="absolute inset-0 flex items-center justify-center pointer-events-none px-8"><div className="scan-frame w-full" style={{aspectRatio:String(aspect),maxWidth:aspect>1?"420px":"300px"}}><span className="scan-frame-corner" style={{top:-2,left:-2,borderTopWidth:4,borderLeftWidth:4,borderTopLeftRadius:16}}/><span className="scan-frame-corner" style={{top:-2,right:-2,borderTopWidth:4,borderRightWidth:4,borderTopRightRadius:16}}/><span className="scan-frame-corner" style={{bottom:-2,left:-2,borderBottomWidth:4,borderLeftWidth:4,borderBottomLeftRadius:16}}/><span className="scan-frame-corner" style={{bottom:-2,right:-2,borderBottomWidth:4,borderRightWidth:4,borderBottomRightRadius:16}}/><span className="scan-line"/></div></div>{flash&&<div className="capture-flash absolute inset-0" style={{background:"#fff"}}/>}</>}
 {phase==="requesting"&&<div className="absolute inset-0 flex flex-col items-center justify-center gap-3 px-8 text-center"><Camera className="w-8 h-8 animate-pulse" style={{color:"rgba(255,255,255,0.6)"}}/><p className="text-sm" style={{color:"rgba(255,255,255,0.7)"}}>Activation de la caméra…</p></div>}
 {phase==="error"&&<div className="absolute inset-0 flex flex-col items-center justify-center gap-4 px-8 text-center"><Camera className="w-8 h-8" style={{color:"rgba(255,255,255,0.5)"}}/><p className="text-sm" style={{color:"rgba(255,255,255,0.8)"}}>Impossible d&apos;accéder à la caméra. Vérifiez l&apos;autorisation caméra de l&apos;application, ou choisissez un fichier existant.</p></div>}
 {phase==="review"&&capturedDataUrl&&<img src={capturedDataUrl} alt="" className="absolute inset-0 w-full h-full object-contain" style={{background:"#000"}}/>}</div>
 <div className="relative z-10 px-6 flex flex-col items-center gap-5" style={{paddingTop:"18px",paddingBottom:"calc(env(safe-area-inset-bottom, 0px) + 22px)"}}>
 {phase!=="review"&&<div className="text-center"><p className="text-white font-semibold text-[15px]">{VAULT_DOCUMENT_LABELS[kind]}</p><p className="text-sm mt-0.5" style={{color:"rgba(255,255,255,0.65)"}}>{VAULT_DOCUMENT_SCAN_INSTRUCTIONS[kind]}</p></div>}
 {phase==="camera"&&<div className="flex items-center gap-8"><button type="button" onClick={()=>fileInputRef.current?.click()} aria-label="Choisir un fichier" className="focus-gold w-11 h-11 rounded-full flex items-center justify-center" style={{background:"rgba(255,255,255,0.12)"}}><Upload className="w-4 h-4" style={{color:"#fff"}}/></button><button type="button" onClick={capture} aria-label="Prendre la photo" className="focus-gold w-[68px] h-[68px] rounded-full flex items-center justify-center" style={{background:"#fff",border:"4px solid rgba(255,255,255,0.35)"}}><span className="w-full h-full rounded-full" style={{background:"#fff"}}/></button><span className="w-11 h-11"/></div>}
 {(phase==="error"||phase==="requesting")&&<button type="button" onClick={()=>fileInputRef.current?.click()} className="focus-gold inline-flex items-center gap-2 text-sm font-semibold px-5 py-2.5 rounded-full" style={{background:"var(--color-gold)",color:"#0a1f1c"}}><Upload className="w-4 h-4"/>Choisir un fichier</button>}
 {phase==="review"&&<div className="flex items-center gap-3 w-full max-w-sm"><button type="button" onClick={retake} className="focus-gold flex-1 inline-flex items-center justify-center gap-2 text-sm font-semibold px-5 py-3 rounded-full" style={{background:"rgba(255,255,255,0.12)",color:"#fff"}}><RotateCcw className="w-4 h-4"/>Reprendre</button><button type="button" onClick={confirmCapture} className="focus-gold flex-1 inline-flex items-center justify-center gap-2 text-sm font-semibold px-5 py-3 rounded-full" style={{background:"var(--color-gold)",color:"#0a1f1c"}}><Check className="w-4 h-4"/>Valider</button></div>}
 <input ref={fileInputRef} type="file" accept="image/*,.pdf" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)handleFilePicked(file);e.target.value="";}}/></div></div>;
}