"use client";
import Link from "next/link";
import { Check, ExternalLink, HelpCircle, Sparkles, X } from "lucide-react";
import { DISPOSITIFS } from "@/lib/dispositifs";
import { getOrganisme } from "@/lib/organismes";
import { getConnector, hasCapability, type ConnectorCapability } from "@/lib/connectors";
import { CONNECTOR_CAPABILITY_LABELS } from "@/lib/applicationTemplate";
import { vibrate } from "@/lib/haptics";
import { openExternal } from "@/lib/openExternal";
import { DISPOSITIF_TRACKING_STATUSES, DISPOSITIF_TRACKING_STATUS_LABELS, DISPOSITIF_TRACKING_STATUS_COLORS, type DossierDispositifTracking, type DispositifTrackingStatus } from "@/lib/dossier";
interface DossierFunderRowProps{dossierId:string;tracking:DossierDispositifTracking;onChange:(patch:Partial<DossierDispositifTracking>)=>void;}
const CORE_CAPABILITIES:ConnectorCapability[]=["prefill","document_matching","export"];const FUTURE_CAPABILITIES:ConnectorCapability[]=["assisted_submission","api_submission"];
export function DossierFunderRow({dossierId,tracking,onChange}:DossierFunderRowProps){
 const dispositif=DISPOSITIFS.find(d=>d.id===tracking.dispositifId);if(!dispositif)return null;const organisme=getOrganisme(dispositif.organismeId);const connector=getConnector(organisme.id);const disabled=tracking.status==="non_eligible";const canPrepare=hasCapability(connector,"prefill")&&!disabled;
 return <div className="card p-4"><div className="flex items-center gap-2.5 mb-3"><span className="w-8 h-8 rounded-lg flex items-center justify-center text-[11px] font-bold shrink-0" style={{background:`${organisme.color}22`,color:organisme.color}}>{organisme.name.slice(0,2)}</span><div className="flex-1 min-w-0"><p className="text-sm font-semibold truncate">{dispositif.name}</p><button type="button" onClick={()=>{vibrate();openExternal(dispositif.officialUrl);}} className="focus-gold inline-flex items-center gap-1 text-xs font-medium" style={{color:"var(--color-gold)"}}>Déposer sur le site officiel<ExternalLink className="w-3 h-3"/></button></div></div>
 <div className="flex flex-wrap gap-1.5 mb-3">{[...CORE_CAPABILITIES,...FUTURE_CAPABILITIES].map(cap=>{const available=hasCapability(connector,cap);const isFuture=FUTURE_CAPABILITIES.includes(cap);const Icon=available?Check:isFuture?HelpCircle:X;const color=available?"var(--color-success)":isFuture?"var(--color-text-faint)":"var(--color-error)";return <span key={cap} className="inline-flex items-center gap-1 text-[10px] font-medium px-2 py-1 rounded-full" style={{background:"var(--color-bg-elevated)",color}}><Icon className="w-3 h-3" strokeWidth={3}/>{CONNECTOR_CAPABILITY_LABELS[cap]}{isFuture&&!available?" (à venir)":""}</span>})}</div>
 {canPrepare&&<Link href={`/dossiers/application?dossierId=${dossierId}&dispositifId=${dispositif.id}`} onClick={()=>vibrate()} className="focus-gold mb-3 inline-flex items-center justify-center gap-1.5 w-full text-xs font-semibold px-4 py-2.5 rounded-xl" style={{background:"var(--color-gold-soft)",color:"var(--color-gold)"}}><Sparkles className="w-3.5 h-3.5"/>Préparer ce dossier</Link>}
 <label className="block text-xs mb-1.5" style={{color:"var(--color-text-faint)"}}>Statut auprès de {organisme.name}</label><select value={tracking.status} onFocus={()=>vibrate()} onChange={e=>{vibrate();onChange({status:e.target.value as DispositifTrackingStatus});}} className="focus-gold w-full rounded-xl px-3.5 py-2.5 text-sm outline-none mb-3" style={{background:"var(--color-bg-elevated)",border:"1px solid var(--color-border)",color:DISPOSITIF_TRACKING_STATUS_COLORS[tracking.status]}}>{DISPOSITIF_TRACKING_STATUSES.map(status=><option key={status} value={status} style={{color:"#000"}}>{DISPOSITIF_TRACKING_STATUS_LABELS[status]}</option>)}</select>
 {!disabled&&<div className="grid grid-cols-2 gap-3"><div><label className="block text-xs mb-1.5" style={{color:"var(--color-text-faint)"}}>Montant demandé (€)</label><input type="number" min={0} value={tracking.montantDemande??""} onFocus={()=>vibrate()} onChange={e=>onChange({montantDemande:e.target.value===""?null:Number(e.target.value)})} placeholder="0" className="focus-gold w-full rounded-xl px-3 py-2 text-sm outline-none" style={{background:"var(--color-bg-elevated)",border:"1px solid var(--color-border)",color:"var(--color-text)"}}/></div><div><label className="block text-xs mb-1.5" style={{color:"var(--color-text-faint)"}}>Montant perçu (€)</label><input type="number" min={0} value={tracking.montantPercu??""} onFocus={()=>vibrate()} onChange={e=>onChange({montantPercu:e.target.value===""?null:Number(e.target.value)})} placeholder="0" disabled={tracking.status!=="accepte"} className="focus-gold w-full rounded-xl px-3 py-2 text-sm outline-none disabled:opacity-40" style={{background:"var(--color-bg-elevated)",border:"1px solid var(--color-border)",color:"var(--color-text)"}}/></div></div>}</div>;
}