"use client";
import { useEffect, useRef, useState } from "react";
import { Bell, CheckCheck, Info, AlertTriangle, CheckCircle2, XCircle } from "lucide-react";
import clsx from "clsx";
import { useApplicationStore } from "@/store/useApplicationStore";
import type { NotificationSeverity } from "@/lib/notifications";
import { vibrate } from "@/lib/haptics";
const ICONS: Record<NotificationSeverity, typeof Info> = { info: Info, success: CheckCircle2, warning: AlertTriangle, error: XCircle };
const COLORS: Record<NotificationSeverity, string> = { info:"var(--color-accent)",success:"var(--color-success)",warning:"var(--color-warning)",error:"var(--color-error)" };
function timeAgo(iso:string):string{const diffMs=Date.now()-new Date(iso).getTime();const min=Math.floor(diffMs/60000);if(min<1)return "à l'instant";if(min<60)return `il y a ${min} min`;const h=Math.floor(min/60);if(h<24)return `il y a ${h} h`;return `il y a ${Math.floor(h/24)} j`;}
export function NotificationBell(){const[open,setOpen]=useState(false);const ref=useRef<HTMLDivElement>(null);const notifications=useApplicationStore(s=>s.notifications);const markAllNotificationsRead=useApplicationStore(s=>s.markAllNotificationsRead);const markNotificationRead=useApplicationStore(s=>s.markNotificationRead);const unreadCount=notifications.filter(n=>!n.read).length;useEffect(()=>{function onClick(e:MouseEvent){if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)}document.addEventListener("mousedown",onClick);return()=>document.removeEventListener("mousedown",onClick)},[]);return <div className="relative" ref={ref}><button type="button" onClick={()=>{vibrate();setOpen(o=>!o)}} aria-label="Notifications" className="focus-gold relative w-10 h-10 rounded-full flex items-center justify-center card card-hover"><Bell className="w-[18px] h-[18px]" style={{color:"var(--color-text)"}}/>{unreadCount>0&&<span className="absolute -top-1 -right-1 min-w-[18px] h-[18px] px-1 rounded-full text-[10px] font-semibold flex items-center justify-center" style={{background:"var(--color-gold)",color:"#0a1f1c"}}>{unreadCount}</span>}</button>{open&&<div className="card absolute right-0 mt-2 w-[min(360px,calc(100vw-2.5rem))] max-h-[420px] overflow-y-auto shadow-2xl z-50" style={{boxShadow:"0 20px 40px rgba(0,0,0,0.45)"}}><div className="flex items-center justify-between px-4 py-3" style={{borderBottom:"1px solid var(--color-border)"}}><span className="font-semibold text-sm">Notifications</span>{unreadCount>0&&<button type="button" onClick={()=>{vibrate();markAllNotificationsRead()}} className="text-xs flex items-center gap-1 hover:opacity-80" style={{color:"var(--color-text-muted)"}}><CheckCheck className="w-3.5 h-3.5"/>Tout marquer lu</button>}</div>{notifications.length===0?<p className="px-4 py-6 text-sm text-center" style={{color:"var(--color-text-faint)"}}>Aucune notification pour le moment.</p>:<ul>{notifications.map(n=>{const Icon=ICONS[n.severity];return <li key={n.id}><button type="button" onClick={()=>{vibrate();markNotificationRead(n.id)}} className={clsx("w-full text-left px-4 py-3 flex gap-3 transition-colors hover:bg-white/[0.03]")} style={{borderBottom:"1px solid var(--color-border)"}}><Icon className="w-4 h-4 shrink-0 mt-0.5" style={{color:COLORS[n.severity]}}/><span className="flex-1 min-w-0"><span className="flex items-center gap-2"><span className="text-sm font-medium truncate">{n.title}</span>{!n.read&&<span className="w-1.5 h-1.5 rounded-full shrink-0" style={{background:"var(--color-gold)"}}/>}</span><span className="block text-xs mt-0.5 leading-relaxed" style={{color:"var(--color-text-muted)"}}>{n.message}</span><span className="block text-[11px] mt-1" style={{color:"var(--color-text-faint)"}}>{timeAgo(n.createdAt)}</span></span></button></li>})}</ul>}</div>}</div>}
