"use client";
import { Suspense,useRef,useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { AlertTriangle,ArrowLeft,Check,CheckCircle2,Download,ExternalLink,FileText,HelpCircle,Sparkles,Upload,X } from "lucide-react";
import { useApplicationStore } from "@/store/useApplicationStore";
import { DISPOSITIFS } from "@/lib/dispositifs";
import { getOrganisme } from "@/lib/organismes";
import { getConnector,hasCapability } from "@/lib/connectors";
import { CONNECTOR_CAPABILITY_LABELS,type ConnectorCapability } from "@/lib/applicationTemplate";
import { resolveApplicationInstance,assembleDraft,buildExportSummary,type ResolvedField,type FieldStatus } from "@/lib/applicationEngine";
import type { ApplicationSubmissionRecord } from "@/lib/dossier";
import { makeNotification } from "@/lib/notifications";
import { openExternal } from "@/lib/openExternal";
import { vibrate } from "@/lib/haptics";
const STATUS_META:Record<FieldStatus,{icon:typeof Check;color:string;label:string}>={filled:{icon:Check,color:"var(--color-success)",label:"Rempli"},to_confirm:{icon:HelpCircle,color:"var(--color-warning)",label:"À confirmer"},missing:{icon:X,color:"var(--color-error)",label:"Manquant"}};
const PROVENANCE_LABELS:Record<ResolvedField["provenance"],string>={profile:"Profil",project:"Projet",manual:"Saisie manuelle",draft:"Brouillon"};
const CAPABILITIES_TO_SHOW:ConnectorCapability[]=["prefill","document_matching","export","assisted_submission","api_submission"];
function readFileAsDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=reject;reader.readAsDataURL(file)})}
function DossierApplicationContent(){
 const params=useSearchParams(),dossierId=params.get("dossierId"),dispositifId=params.get("dispositifId");
 const dossier=useApplicationStore(s=>s.dossiers.find(d=>d.id===dossierId)),documents=useApplicationStore(s=>s.documents),profile=useApplicationStore(s=>s.application.applicant_profile);
 const updateField=useApplicationStore(s=>s.updateDossierApplicationField),updateDraft=useApplicationStore(s=>s.updateDossierApplicationDraft),validateApplication=useApplicationStore(s=>s.validateDossierApplication),recordExport=useApplicationStore(s=>s.recordDossierExport),addAttachment=useApplicationStore(s=>s.addDossierProjectAttachment),addNotification=useApplicationStore(s=>s.addNotification);
 const[mode,setMode]=useState<"prepare"|"review">("prepare"),uploadInputRef=useRef<HTMLInputElement>(null),[uploadingRequirementId,setUploadingRequirementId]=useState<string|null>(null);
 const dispositif=DISPOSITIFS.find(d=>d.id===dispositifId),tracking=dossier?.dispositifs.find(t=>t.dispositifId===dispositifId);
 if(!dossier||!dispositif||!tracking)return <div className="max-w-2xl w-full mx-auto px-5 py-16 flex-1 text-center"><p className="text-sm mb-4">Ce dossier ou ce dispositif n&apos;existe plus.</p><Link href="/dossiers">Retour à mes dossiers</Link></div>;
 const organisme=getOrganisme(dispositif.organismeId),connector=getConnector(organisme.id),template=connector.getApplicationTemplate(dispositif.id);
 if(!template)return <div className="max-w-2xl w-full mx-auto px-5 py-16 flex-1 text-center"><AlertTriangle className="w-8 h-8 mx-auto mb-3"/><p className="text-sm mb-1 font-semibold">Préparation assistée indisponible pour {organisme.name}</p><p className="text-sm mb-4">Aucune intégration réelle n&apos;existe encore pour ce dispositif. Déposez directement sur le site officiel.</p><button type="button" onClick={()=>{vibrate();openExternal(dispositif.officialUrl)}} className="focus-gold inline-flex items-center gap-1.5 text-sm font-semibold">Ouvrir le site officiel<ExternalLink className="w-3.5 h-3.5"/></button></div>;
 const manualValues=tracking.manualFieldValues??{},draftValues=tracking.draftValues??{},instance=resolveApplicationInstance(template,profile,dossier.project,documents,manualValues,draftValues),alreadyValidated=Boolean(tracking.submission);
 function generateDraft(fieldId:string){vibrate();updateDraft(dossier!.id,dispositif!.id,fieldId,assembleDraft(fieldId,profile,dossier!.project),false)}
 async function handleUploadedFile(file:File){if(!uploadingRequirementId)return;const requirement=template!.documentRequirements.find(r=>r.id===uploadingRequirementId);if(!requirement)return;if(file.size>8*1024*1024){addNotification(makeNotification("Fichier trop volumineux",`${file.name} dépasse la limite de 8 Mo.`,"error"));return}const dataUrl=await readFileAsDataUrl(file);addAttachment(dossier!.id,{id:crypto.randomUUID(),label:requirement.label,fileName:file.name,dataUrl,uploadedAt:new Date().toISOString()});setUploadingRequirementId(null)}
 function handleValidate(){vibrate();const submission:ApplicationSubmissionRecord={templateId:template!.id,templateVersion:template!.version,validatedAt:new Date().toISOString(),validatedByName:profile.name||profile.email||"Utilisateur Subvento",fieldsSnapshot:instance.fields.map(f=>({fieldId:f.field.id,label:f.field.label,value:f.value,provenance:f.provenance})),documentsSnapshot:instance.documents.map(d=>({requirementId:d.requirement.id,label:d.requirement.label,fileName:d.match?d.match.fileName:null})),depositMode:null,exportedAt:null,confirmationRef:null};validateApplication(dossier!.id,dispositif!.id,submission)}
 function handleExport(){vibrate();const output=buildExportSummary(template!,organisme,dispositif!,instance,dossier!.project.title||""),blob=new Blob([output],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`subvento-${dispositif!.id.toLowerCase()}.txt`;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);recordExport(dossier!.id,dispositif!.id)}
 const canValidate=instance.requiredFieldsMissing===0&&instance.requiredDocumentsFound===instance.requiredDocumentsTotal;
 return <div className="max-w-2xl w-full mx-auto px-5 py-8 sm:py-12 flex-1"><Link href={`/dossiers/detail?id=${dossier.id}`} onClick={()=>vibrate()} className="focus-gold inline-flex items-center gap-1.5 text-sm mb-5"><ArrowLeft className="w-4 h-4"/>{dossier.project.title||"Dossier"}</Link><h1 className="text-xl font-semibold tracking-tight mb-1">{dispositif.name}</h1><p className="text-sm mb-4">{organisme.fullName}</p><div className="rounded-xl px-4 py-3 mb-5 text-xs leading-relaxed">{template.generationNote}</div><div className="flex flex-wrap gap-1.5 mb-6">{CAPABILITIES_TO_SHOW.map(cap=>{const available=hasCapability(connector,cap),Icon=available?Check:HelpCircle;return <span key={cap} className="inline-flex items-center gap-1 text-[10px] font-medium px-2 py-1 rounded-full"><Icon className="w-3 h-3"/>{CONNECTOR_CAPABILITY_LABELS[cap]}</span>})}</div>
 {mode==="prepare"&&<><div className="card p-4 mb-6"><div className="flex justify-between mb-2"><span className="text-sm font-medium">Complétude</span><span className="text-sm font-semibold">{instance.completeness}%</span></div><div className="h-1.5 rounded-full overflow-hidden mb-3"><div className="h-full rounded-full" style={{width:`${instance.completeness}%`,background:"linear-gradient(90deg, var(--color-accent), var(--color-gold))"}}/></div><div className="flex flex-wrap gap-x-4 gap-y-1 text-xs"><span>{instance.requiredFieldsFilled}/{instance.requiredFieldsTotal} champs remplis</span>{instance.requiredFieldsToConfirm>0&&<span>{instance.requiredFieldsToConfirm} à confirmer</span>}{instance.requiredFieldsMissing>0&&<span>{instance.requiredFieldsMissing} manquant{instance.requiredFieldsMissing>1?"s":""}</span>}<span><FileText className="w-3 h-3 inline mr-1"/>{instance.requiredDocumentsFound}/{instance.requiredDocumentsTotal} documents</span></div></div>
 <h2 className="text-sm font-semibold mb-2">INFORMATIONS DU DOSSIER</h2><div className="flex flex-col gap-2.5 mb-6">{instance.fields.map(resolved=>{const meta=STATUS_META[resolved.status],Icon=meta.icon,draft=draftValues[resolved.field.id];return <div key={resolved.field.id} className="card p-3.5"><div className="flex justify-between gap-2 mb-1.5"><span className="text-sm font-medium">{resolved.field.label}{resolved.field.required&&<span className="ml-1">*</span>}</span><span className="flex items-center gap-1 text-[11px]"><Icon className="w-3 h-3"/>{meta.label}</span></div>{resolved.field.helpText&&<p className="text-xs mb-1.5">{resolved.field.helpText}</p>}{resolved.field.draftable&&draft&&!draft.accepted?<><textarea value={draft.text} onChange={e=>updateDraft(dossier.id,dispositif.id,resolved.field.id,e.target.value,false)} rows={3} className="focus-gold w-full rounded-lg px-3 py-2 text-sm mb-2"/><div className="flex gap-2"><span className="text-[10px]">Brouillon généré — à valider</span><button type="button" onClick={()=>updateDraft(dossier.id,dispositif.id,resolved.field.id,draft.text,true)} className="text-xs font-semibold">Accepter</button><button type="button" onClick={()=>generateDraft(resolved.field.id)} className="text-xs">Régénérer</button></div></>:resolved.field.type==="textarea"?<textarea value={manualValues[resolved.field.id]??resolved.value} onChange={e=>updateField(dossier.id,dispositif.id,resolved.field.id,e.target.value)} rows={3} className="focus-gold w-full rounded-lg px-3 py-2 text-sm"/>:<input type={resolved.field.type==="number"?"number":resolved.field.type==="date"?"date":"text"} value={manualValues[resolved.field.id]??resolved.value} onChange={e=>updateField(dossier.id,dispositif.id,resolved.field.id,e.target.value)} className="focus-gold w-full rounded-lg px-3 py-2 text-sm"/>}{resolved.field.draftable&&(!draft||draft.accepted)&&!resolved.value&&<button type="button" onClick={()=>generateDraft(resolved.field.id)} className="focus-gold mt-2 inline-flex items-center gap-1.5 text-xs font-semibold"><Sparkles className="w-3.5 h-3.5"/>Générer un brouillon</button>}{resolved.value&&<p className="text-[11px] mt-1.5">Source : {PROVENANCE_LABELS[resolved.provenance]}</p>}</div>})}</div>
 <h2 className="text-sm font-semibold mb-2">DOCUMENTS REQUIS</h2><div className="flex flex-col gap-2 mb-6">{instance.documents.map(d=><div key={d.requirement.id} className="card p-3.5 flex items-center justify-between gap-3"><div className="min-w-0 flex items-center gap-2.5">{d.match?<Check className="w-4 h-4"/>:<X className="w-4 h-4"/>}<div className="min-w-0"><p className="text-sm font-medium truncate">{d.requirement.label}{d.requirement.required&&<span className="ml-1">*</span>}</p><p className="text-xs truncate">{d.match?d.match.fileName:"Non trouvé dans le coffre-fort ou les pièces jointes"}</p></div></div>{!d.match&&(d.requirement.vaultKind?<Link href="/documents" className="text-xs font-semibold">Ajouter</Link>:<button type="button" onClick={()=>{setUploadingRequirementId(d.requirement.id);uploadInputRef.current?.click()}} className="text-xs font-semibold"><Upload className="w-3.5 h-3.5 inline"/> Ajouter</button>)}</div>)}</div><input ref={uploadInputRef} type="file" accept=".pdf,image/*" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)handleUploadedFile(file);e.target.value=""}}/>
 <h2 className="text-sm font-semibold mb-2">CONTRÔLES DE COHÉRENCE</h2><div className="card px-4 mb-6">{instance.checks.map(c=><div key={c.id} className="flex items-center gap-2.5 py-2.5">{c.passed?<CheckCircle2 className="w-4 h-4"/>:<AlertTriangle className="w-4 h-4"/>}<span className="text-sm">{c.label}</span></div>)}</div><button type="button" onClick={()=>{vibrate();setMode("review")}} className="focus-gold w-full text-sm font-semibold px-6 py-3 rounded-full">Vérifier mon dossier</button></>}
 {mode==="review"&&!alreadyValidated&&<ReviewPanel instance={instance} organisme={organisme.fullName} dispositif={dispositif.name} onBack={()=>setMode("prepare")} canValidate={canValidate} onValidate={handleValidate}/>}
 {mode==="review"&&alreadyValidated&&tracking.submission&&<DepositPanel submission={tracking.submission} officialUrl={dispositif.officialUrl} canExport={hasCapability(connector,"export")} canAssisted={hasCapability(connector,"assisted_submission")} canApi={hasCapability(connector,"api_submission")} onExport={handleExport} onBack={()=>setMode("prepare")}/>}</div>
}
function ReviewPanel({instance,organisme,dispositif,onBack,canValidate,onValidate}:{instance:ReturnType<typeof resolveApplicationInstance>;organisme:string;dispositif:string;onBack:()=>void;canValidate:boolean;onValidate:()=>void}){return <div><button type="button" onClick={onBack} className="focus-gold inline-flex items-center gap-1.5 text-sm mb-4"><ArrowLeft className="w-4 h-4"/>Retour à la préparation</button><h2 className="text-lg font-semibold mb-1">Validation avant dépôt</h2><p className="text-sm mb-4">Vérifiez ce qui sera considéré comme votre dossier {dispositif} — {organisme}. Rien n&apos;est envoyé automatiquement : le dépôt reste une action que vous effectuez vous-même sur le site officiel.</p><div className="card px-5 mb-4">{instance.fields.map(f=><div key={f.field.id} className="flex justify-between gap-4 py-2.5"><span className="text-sm">{f.field.label}</span><span className="text-sm font-medium text-right">{f.value||"—"}</span></div>)}</div><div className="card px-5 mb-4">{instance.documents.map(d=><div key={d.requirement.id} className="flex justify-between gap-4 py-2.5"><span className="text-sm">{d.requirement.label}</span><span className="text-sm font-medium text-right">{d.match?d.match.fileName:"Manquant"}</span></div>)}</div>{!canValidate&&<div className="rounded-xl px-4 py-3 mb-4 text-xs">Des champs ou documents obligatoires manquent encore — complétez-les avant de valider.</div>}<button type="button" disabled={!canValidate} onClick={onValidate} className="focus-gold w-full text-sm font-semibold px-6 py-3 rounded-full disabled:opacity-40">Je valide et confirme l&apos;exactitude de ces informations</button></div>}
function DepositPanel({submission,officialUrl,canExport,canAssisted,canApi,onExport,onBack}:{submission:ApplicationSubmissionRecord;officialUrl:string;canExport:boolean;canAssisted:boolean;canApi:boolean;onExport:()=>void;onBack:()=>void}){return <div><button type="button" onClick={onBack} className="focus-gold inline-flex items-center gap-1.5 text-sm mb-4"><ArrowLeft className="w-4 h-4"/>Retour à la préparation</button><div className="card p-4 mb-4 flex gap-2.5"><CheckCircle2 className="w-5 h-5"/><div><p className="text-sm font-semibold">Dossier validé</p><p className="text-xs">Validé par {submission.validatedByName} le {new Date(submission.validatedAt).toLocaleString("fr-FR")}{submission.exportedAt?` · Exporté le ${new Date(submission.exportedAt).toLocaleString("fr-FR")}`:""}</p></div></div><h2 className="text-sm font-semibold mb-2">DÉPÔT</h2><div className="card p-4 mb-3"><p className="text-sm font-semibold mb-1">Mode export</p><p className="text-xs mb-3">Subvento génère un récapitulatif de votre dossier. Vous le déposez vous-même sur le portail officiel.</p>{canExport?<div className="flex flex-col sm:flex-row gap-2"><button type="button" onClick={onExport} className="focus-gold text-sm font-semibold px-4 py-2.5 rounded-xl"><Download className="w-4 h-4 inline"/> Télécharger mon dossier prêt</button><button type="button" onClick={()=>openExternal(officialUrl)} className="focus-gold text-sm font-semibold px-4 py-2.5 rounded-xl"><ExternalLink className="w-3.5 h-3.5 inline"/> Ouvrir le portail officiel</button></div>:<p className="text-xs">Indisponible pour ce dispositif.</p>}</div><div className="card p-4 mb-3 opacity-60"><p className="text-sm font-semibold mb-1">Dépôt assisté</p><p className="text-xs">{canAssisted?"Disponible.":"Non disponible — aucun accompagnement au dépôt n'existe encore pour cet organisme."}</p></div><div className="card p-4 opacity-60"><p className="text-sm font-semibold mb-1">Dépôt automatique (API)</p><p className="text-xs">{canApi?"Disponible.":"Indisponible — aucune intégration officielle n'existe à ce jour. Subvento ne contourne jamais un portail (CAPTCHA, MFA…) pour déposer à votre place."}</p></div></div>}
export default function DossierApplicationPage(){return <Suspense fallback={null}><DossierApplicationContent/></Suspense>}